### ISSUE TITLE
tapping the add marker on mobile web should send you to the app (based on platform)

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#120]

**Comment by amitaibu** [comment]
This work for iOs as there's no Android package yet.

**Comment by ceoaliongroo** [comment]
@mushon have a device Android?, please add to your account testflight.

**Comment by mushon** [comment]
I won't be able to test on Android before I return to Tel Aviv 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon
