### ISSUE TITLE
Setup a testing account for pre AppStore iOS installs

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#124]
We need to make sure people can install and use the app as of tomorrow. In fact I haven't installed it on my phone yet, and as of now all my tests have been browser based. 

@niryariv mentioned an option for beta testers and in case the app confirmation is postponed. Let's do it.

**Comment by mushon** [comment]
It was this one: https://testflightapp.com

**Comment by ceoaliongroo** [comment]
Ready to iOS
