### ISSUE TITLE
After recording and approving can't log into facebook or post annonymously

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#126]
*tested on Testflight

**Comment by ceoaliongroo** [comment]
Resolve with the version 1.0.0 build 3 

![build3](https://f.cloud.github.com/assets/2622152/1464321/98743dce-4544-11e3-9891-ed898aa6fc69.png)

**Comment by mushon** [comment]
ok, I can see it working now.
@amitaibu, please tell me we will not see this problem in the version we submitted to the app store.

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)

**Comment by ceoaliongroo** [comment]
@mushon The error was creating the build 1.0.0 build 2 for test flight...

The version in itunes it's ok! for post facebook or annonymously.

**Comment by mushon** [comment]
Great, that's what I wanted to hear :)  

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)
