### ISSUE TITLE
app starts to record in delay

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#129]
the visual display of the recording appears before the device starts recording which results in the audio begining being clipped

**Comment by ceoaliongroo** [comment]
@mushon 

Was not possible reproduce the error. 

Seems fine in ipad 2  ver.6.0.3 , iphone 4 iOS ver.7.0.3. and Android Tablet ver.4.2.2

![ipad-before](https://f.cloud.github.com/assets/2622152/1472644/a076669c-4606-11e3-92b2-c912e899fd81.png)
![ipad-record](https://f.cloud.github.com/assets/2622152/1472645/a099333e-4606-11e3-9ed2-96b6b9269716.png)
![iphone-before](https://f.cloud.github.com/assets/2622152/1472646/a0b51f54-4606-11e3-8083-a7ba5e4b1153.png)
![iphone-record](https://f.cloud.github.com/assets/2622152/1472647/a0bbb4c2-4606-11e3-8667-e503fb477e58.png)

**Comment by mushon** [comment]
Ok, I will check on some other devices

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by amitaibu** [comment]
Please re-open if needed.

**Comment by mushon** [comment]
Yeah, it didn't happen again, so that's fine. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon
