### ISSUE TITLE
Use icon to show my current location

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#130]
You should use this one:
![urhere.png](https://raw.github.com/Gizra/public_education/master/app/images/urhere@2x.png)
From:
https://raw.github.com/Gizra/public_education/master/app/images/urhere@2x.png

**Comment by amitaibu** [comment]
Assigned to @mushon for CSS cleanup.

**Comment by amitaibu** [comment]
Actually, reassigned to @ceoaliongroo as no CSS is needed, we need to fix the icon's image location on `grunt build`

**Comment by mushon** [comment]
I think this can be closed now, no?
