### ISSUE TITLE
When looping through locations remember the placemark panel state

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#137]
If the user chose to fold the panel, keep it folded.

(this is important towards the launch)

**Comment by amitaibu** [comment]
Please explain (what it placemark panel state)

**Comment by mushon** [comment]
I mean the `<<     >    >>` with the text and flag and all  

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)

**Comment by amitaibu** [comment]
The panel is folded by default. When you cycle through all the markers via web, it will keep it open. Do you want another behaviour?

**Comment by mushon** [comment]
Yes, 
If I started the cycle and then folded the panel it should maintain its state in the following markers as well. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by mushon** [comment]
I cannot see this in the latest merge into gh-pages, are you sure it's there? It opens for me the panel opens with every new marker. Please check again, reopening.

**Comment by amitaibu** [comment]
Current logic is to always keep open on cycle. Change it?

‫ב-6 בנוב 2013, בשעה 16:24, ‏Mushon Zer-Aviv notifications@github.com כתב/ה:‬

**Comment by mushon** [comment]
Yes, the logic should be to always maintain the latest state the user asked (whether open or closed)

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)

**Comment by amitaibu** [comment]
Pushed fix to gh-pages.
