### ISSUE TITLE
Certificate Revoke 

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/public_education#150]
@mushon, i thin the certificate generated by XCode revoked it's need to debug or release the application.  and It's not need for TestFlight. 

The TestFlight use other certificate generated the last week 

![screen shot 2013-11-05 at 6 19 36 pm](https://f.cloud.github.com/assets/2622152/1475215/1070ac32-4639-11e3-91b9-f0532afc65c9.png)

With the Provisioning Profiles:
- Public Education 1.0.0
- Public Education 1.0.0 Dev

Sorry for the mail, it's was generated for a conflict with certificates in the configuration of a new XCode in a new computer here.
### To fix:

Could you check in your XCode you can debug the application. I think that XCode fixed automatic. 

When you click on "play" XCode will ask "Fix permission" and XCode recreate the certificate in the Provisioning Profiles site. 

@amitaibu, if @mushon have any problem i think we can export the certificate from your "Keychain Access" and send it to him.

Or 

Use this procedure:
https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html#//apple_ref/doc/uid/TP40012582-CH31-SW16

**Comment by mushon** [comment]
ok, just wanted to make sure we haven't rolled a week back.
I guess we're good.
Thanks for the reassuring update. 
We can probably close this one now.

**Comment by amitaibu** [comment]
Carlos you are awesome! Thanks for the detailed update.

‫ב-5 בנוב 2013, בשעה 18:55, ‏Mushon Zer-Aviv notifications@github.com כתב/ה:‬

**Comment by mushon** [comment]
+1

**Comment by niryariv** [comment]
Thanks Carlos!
