### ISSUE TITLE
Can't see markers in latest beta (4)

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#151]
In beta (4) app:
![img_3389](https://f.cloud.github.com/assets/27123/1475693/596ee088-463f-11e3-8bd1-d443479d5759.PNG)

In mobile website:
![img_3390](https://f.cloud.github.com/assets/27123/1475694/5bf64f08-463f-11e3-92bc-dafea418f42c.PNG)

**Comment by ceoaliongroo** [comment]
Hi @mushon 

The ver. 1.0.0 build (4) works fine in the ipad. Load Tel aviv markers. 
![build 4 - qa](https://f.cloud.github.com/assets/2622152/1480465/9849f988-46ac-11e3-9c2b-d62a942cb3bc.png)

I rebuild ver. 1.0.0 build (5) load the markers in Istambul
**Suggest delete the app in your phone first and then install the new build. (Just to be sure)**

![build 5](https://f.cloud.github.com/assets/2622152/1480496/6e268512-46ad-11e3-9abd-5fe87e29522c.png)

I only see an unusual behaviour, after add a new marker with facebook all markers disappears from the map. Just happens to me one time and wait 1 minute then got all the markers from the server. 

If it's possible reproduce again, we open a new issue.
