### ISSUE TITLE
Facebook login gets stuck with no feedback

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#156]
Trying to log into Facebook gets you stuck on a white screen:
![img_3392](https://f.cloud.github.com/assets/27123/1481668/44656ba0-46ce-11e3-90f3-5ed63534bfc9.PNG)

I got fixed after quitting and relaunching the app a few times and trying again.
It happened to me in the latest build too.

**Comment by ceoaliongroo** [comment]
Related #136
