### ISSUE TITLE
add 'koc' class on body tag for custom css features

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#158]
I would like to use slightly different stylings for the Koc University display, right now I do it by explicitly targeting the 1080x1920px resolution of the portrait screen we use there but I would rather prefer to do it through a custom `koc` class on the body tag. I would suggest toggle the class on and off by clicking `shift + k`. But I'm open to other ideas too.

What do you suggest?

**Comment by amitaibu** [comment]
Instead lets use query string `?koc=1`

**Comment by amitaibu** [comment]
Is this for all pages, or just the main page?

**Comment by mushon** [comment]
for all pages  

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)

**Comment by amitaibu** [comment]
this can't be on the body tag, it needs to be on a wrapper for every angular page by itself.

**Comment by amitaibu** [comment]
@ceoaliongroo 

Add a `toggle-class` router, to enables/ disables from localStorage  classes from config.json

redirect back to main.

**Comment by mushon** [comment]
actually it is only relevant in main and in play-marker, so hopefully that makes things easier.
