### ISSUE TITLE
Last master commit broken the add marker

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/public_education#162]
![screen shot 2013-11-06 at 6 09 57 pm](https://f.cloud.github.com/assets/2622152/1484030/155e8ab6-4701-11e3-887b-3679f95452a6.png)

Create the tag for this commit
6a8b90c3ceb35d00db963524763f918e65b0258a
pre-release 1.0.6

**Comment by amitaibu** [comment]
Make sure to bower update. We should probably use angular leaflet's latest tag version

‫ב-6 בנוב 2013, בשעה 18:32, ‏Carlos Mantilla notifications@github.com כתב/ה:‬

**Comment by ceoaliongroo** [comment]
ok updated works!

bower install       angular-leaflet#13a6e1a5a9

**Comment by mushon** [comment]
What do I need to pull to be able to see the add-marker again?

**Comment by amitaibu** [comment]
Try: `bower update`

‫ב-6 בנוב 2013, בשעה 19:08, ‏Mushon Zer-Aviv notifications@github.com כתב/ה:‬

**Comment by mushon** [comment]
didn't work.  
Never mind, I am working on my own branch. Will pull this fix when you push new changes.

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)
