### ISSUE TITLE
Markers should get their geolocations from the user's choice, not from 4sq

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#166]
It seems like the geolocations of the markers are overwritten by that of the closest 4sq places. This should definitely not work that way. For example, I placed a marker in the middle of the Bosphorus. After saving I couldn't find my marker and I finally found it on the bank of the river marked as "Çengelköy Sahili" (which is apparently some place on the other side of the river). This is a critical fix,

**Comment by amitaibu** [comment]
Re-opening, the current position isn't always the first marker, so the CSS is wrong.

**Comment by amitaibu** [comment]
Re-opened wrong issue.
