### ISSUE TITLE
The cycle doesn't change location it's all in tel aviv

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#174]
@amitaibu this kinda borks the opening :/

**Comment by ceoaliongroo** [comment]
Do you want delete all the data from database, now?

**Comment by mushon** [comment]
No

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by ceoaliongroo** [comment]
ok

**Comment by mushon** [comment]
Erasing the Tel Aviv entries could help because the cycle gets stuck there

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by amitaibu** [comment]
Cycle is working properly for me on pe.mushon.com, including http://pe.mushon.com/#/play-marker/4be90f31aecb76b0cec05a80

**Comment by mushon** [comment]
Yes, I have no idea why it happened. The work was well received though. Have you packaged the Android app?The button on the site doesn't work.
