### ISSUE TITLE
Add Android app link or hide its button

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#176]
The current site is deceiving in how it invites you to download the Android app but doesn't provide a link. 
It's good opportunity to add the link and other commits currently in master.

**Comment by amitaibu** [comment]
@ceoaliongroo please add APK to the repo, so we can link to it - so we can avoid waiting for Google play

**Comment by amitaibu** [comment]
Also, it's a good time to check the Google Store link -- why it doesn't work.

**Comment by ceoaliongroo** [comment]
@amitaibu 
1. I moved the APK directly to Production.
   ![screen shot 2013-11-13 at 9 43 20 am](https://f.cloud.github.com/assets/2622152/1529549/fb413e76-4c37-11e3-836c-f0fd33dd627a.png)
2. I researched and found that **we need a google+ community** in other to manage the access to the Alpha or Beta APK. 
   https://plus.google.com/communities/103344450363163291073/members

http://johncblandii.com/2013/05/google-play-developer-console-alpha-testing.html 
https://support.google.com/googleplay/android-developer/answer/3131213

**Comment by ceoaliongroo** [comment]
Works in Chrome Android (Tablet Asus) download the file and install the apk. 

Direct download did it in drive of Gizra, It was not possible create the direct download in github.

**Comment by amitaibu** [comment]
Pushed to gh-pages.
