### ISSUE TITLE
change app name/id

### ISSUE THREAD

**Issue by niryariv** [Gizra/public_education#25]
PubicEducation -> PublicEducation
com.gizra.pubedu -> com.gizra.publiceducation

**Comment by mushon** [comment]
PubicEducation -> LOL  

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)

**Comment by niryariv** [comment]
@mushon I didn't task this earlier because I enjoyed this typo, but now it's confusing my XCode app signatures so we'll have to bid it farewell..
