### ISSUE TITLE
App Store?

### ISSUE THREAD

**Issue by niryariv** [Gizra/public_education#26]
@mushon, any idea if there's a way to pre-register the app in the app store (eg perhaps if you already have some other apps there)?

In the meantime, we could use a dev version which IIRC allows for up to 100 devices or so, using a string that's sent to each user (and the Android version, which doesn't require the app store process)

**Comment by mushon** [comment]
I don't have previous apps in the store. Should we create an account there or something?

**Comment by niryariv** [comment]
let's discuss on Sun
