### ISSUE TITLE
Develop the markup some more so I can dive into it

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#37]
At its current stage it was easy for me to work with the map screen but it is harder for me to dive into the other screens. I would appreciate it if you guys could build them out just slightly better so I can more easily dive into them.
If the page had some more markup for me to work with it could've helped. Same goes for the authoring flow.
Call me: 054-3233785

**Comment by ceoaliongroo** [comment]
Ok, Could address an example into the code? I like to understood fine what you need

**Comment by amitaibu** [comment]
@mushon are we talking about the Add marker page for example? Just confirming - adding wrapping divs isn't enough?

**Comment by mushon** [comment]
It's just that I open the other pages and am a bit lost. I would appreciate something that slightly resembles the composition in the sketches and then I could continue working from there.

**Comment by amitaibu** [comment]
[Add marker](https://github.com/Gizra/public_education/blob/master/app/views/add-marker.html) should already have the correct [layout](https://f.cloud.github.com/assets/27123/1132397/f39ef3fa-1bc9-11e3-8a65-4a38160a9861.png). for example, looking at

``` html
<div class="map-wrapper" ng-show="state == 'mark'">
  <div class="instructions-wrapper">
    <div ng-show="center.zoom >= 16">
      Select place.
    </div>

    <div ng-show="center.zoom < 16">
      You need to zoom.
    </div>

    <a href="/#">X</a>
  </div>

  <leaflet center="center" markers="markers" defaults="defaults"></leaflet>

  <div class="location-wrapper" ng-show="center.zoom >= 16">
    <div class="venue">
      {{markers.marker.venue.name | venueName}}
    </div>

    <a class="confirm" ng-show="markers.marker.venue.name.length" ng-click="setState('form')">V</a>
  </div>
</div>

```

You can add/ change your elements inside the `instructions-wrapper` and `location-wrapper`

**Comment by amitaibu** [comment]
If still not clear, give me a ping.

**Comment by mushon** [comment]
ok,
I think I see what threw me off.  
When I hit add-marker it jumped me to the previously added marker (further in the flow) and I wasn't clear on what it is I am seeing.
I backed up a bit and it's clearer now. I will continue from here and will ping you if I have more questions.
Do you have my current location as an element on the page yet? It could help.
cheers,
M.

**Comment by amitaibu** [comment]
Sababa.

> Do you have my current location as an element on the page yet?

Not yet, as we are focusing on the server side for now.
