### ISSUE TITLE
Create user interface to manage markers

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/public_education#53]
Related with the Public Education Server issues 13, 14, 15.

After login can update or delete the user markers. Created simple UI to make test with server.

**Comment by mushon** [comment]
As far as flagging goes, we should have a way to mark some of the markers as "filtered from display loop". That way they will be accessible on the mobile app but not in the university's display. That would answer for some of the University's concern, while not giving them too strong tools for curbing freedom of speech.

**Comment by ceoaliongroo** [comment]
All admin functionality will move to admin proyect
https://github.com/Gizra/public-education-admin/pull/3
