### ISSUE TITLE
Change marker to marker-icon.png to Add_btn@2x.png

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#54]
(in the add marker screen)

@niryariv says this should give us some reference:
http://leafletjs.com/examples/custom-icons.html

**Comment by amitaibu** [comment]
![localhost_9000___add-marker](https://f.cloud.github.com/assets/125707/1415339/f5d75b12-3ef6-11e3-85ad-e2fd3e72d5ae.jpg)

**Comment by ceoaliongroo** [comment]
The component hava an example call markers-icon-example.html may could help us, to find a way using some component property.

**Comment by amitaibu** [comment]
@mushon You can change the class [here](https://github.com/Gizra/public_education/blob/master/app/scripts/controllers/addMarker.js#L19)

**Comment by mushon** [comment]
@amitaibu nice, though not precise. you used `marker@2x.png` and you were supposed to use `Add_btn@2x.png`

**Comment by amitaibu** [comment]
@mushon you can change the class, and use the required image.
