### ISSUE TITLE
Look into Apple App store submission process

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#56]
- [x] IS_MOBILE == true
- [x] [Facebook](http://oauth.uservoice.com/forums/214907-general/suggestions/4807691-error-on-facebook-login-in-this-site-as-well-?tracking_code=93ab7ef15159c13208dcb03a7ff67b14) privacy policy 
- [x] icons (#96)
- [x] Verify on devices and tag version
- [x] Submit app

**Comment by mushon** [comment]
Icons required:
pre-retina: 57_57px
retine: 114_114px

**Comment by mushon** [comment]
We have the [instructions here](http://www.idev101.com/code/Distribution/checklist.html), but generally we should do it through here [iTunes Connect](https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa) which I will as sson as my enrollment in the developer program is  confirmed.

**Comment by amitaibu** [comment]
Added a Git [tag](https://github.com/Gizra/public_education/tree/1.0.0-rc.1)

**Comment by ceoaliongroo** [comment]
@amitabu Tag version work fine, just share button work partially

**Comment by ceoaliongroo** [comment]
Uploaded we need to wait for iTunes...
![image](https://f.cloud.github.com/assets/125707/1435518/6cae693c-4141-11e3-974f-55acfadec44c.png)

@mushon @amitaibu I received this warnings about the icons... during the validation in iTunes
![screen shot 2013-10-30 at 10 41 02 am](https://f.cloud.github.com/assets/2622152/1435537/4f6086d4-4142-11e3-8344-3d6a6c223aa0.png)
