### ISSUE TITLE
Design mockup for playing mode

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#6]

**Comment by mushon** [comment]
Pretty self explanatory. If not, please ask.
![public_education_post_active](https://f.cloud.github.com/assets/27123/1147781/885cc5e8-1eaf-11e3-84c9-fe20564a1e74.png)

**Comment by mushon** [comment]
@niryariv close this if you think this is conclusive enough. Reply here or open a new issue if you need more input.

**Comment by amitaibu** [comment]
@mushon 
1) what is the purpose of the bottom right icon? 
2) do we show the text entered by the user?

**Comment by amitaibu** [comment]
btw, @mushon you can also `git pull` and add CSS for the player page.
