### ISSUE TITLE
Provide app icons

### ISSUE THREAD

**Issue by amitaibu** [Gizra/public_education#84]
@mushon do we have those icons already?

![publiceducation xcodeproj](https://f.cloud.github.com/assets/125707/1415670/fe8a818e-3f15-11e3-9d4d-d193a26123ba.jpg)

**Comment by mushon** [comment]
@ceoaliongroo do we really need ALL of these formats? We are not trying to target tablets at this point. If we do need all of these, please let me know where should I upload them to

**Comment by mushon** [comment]
AFAIK this is done.
