### ISSUE TITLE
Use app icons when building for iOS

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#96]
icon.png & icon@2x.png are available in the images folder:

![icon](https://github.com/Gizra/public_education/raw/master/app/images/icon.png)
![retina icon](https://github.com/Gizra/public_education/raw/master/app/images/icon@2x.png)

**Comment by amitaibu** [comment]
@mushon 

![itunes_connect](https://f.cloud.github.com/assets/125707/1428814/cd6ba6b6-40a8-11e3-937a-4c0b0358913c.jpg)

![itunes_connect](https://f.cloud.github.com/assets/125707/1428823/daff1dc6-40a8-11e3-9603-cc4834c434b9.jpg)

![itunes_connect](https://f.cloud.github.com/assets/125707/1428829/e5da1b4c-40a8-11e3-8e26-00f26be33e65.jpg)

![itunes_connect](https://f.cloud.github.com/assets/125707/1428832/f14cf03a-40a8-11e3-92f1-92d1b5f9b544.jpg)

**Comment by amitaibu** [comment]
> You must enter one or more keywords for your app in English.
> You must provide an app description for English
> You must upload a large app icon.
> You must upload at least one screenshot.

One screenshot would be enough it seems. We need also description text.

**Comment by mushon** [comment]
Adding @ceoaliongroo 

Here's the app info for the app store

App Name:
`Public Education`

Keywords:
`map, audio, command, record, geolocation, croudsourcing, geocaching, public space, art, art app`

Description:

```
Command and educate the networked public.
Record short commands and geocache them anywhere on the map to later be commanded at people passing by.

“In a cross-cultural comparison, the average number of commands (an indicator of behavioral control) issued by Turkish mothers was 14.5 per minute in a community sample of Turkish parents, whereas this number ranged between 1.5 and 9 per minute among the mothers of Head Start children, the mothers of children with ADHD, and the mothers who were referred to family protective services in the U.S.”
—Dr. Nazli Baydar, Running head: Parental Control and Externalizing Behaviors

Public Education is a work inspired by the surprising findings of Dr. Nazli Baydar and other Koç University researchers concerning the unique education styles of Turkish mothers. While the mothers interaction with their children is very commanding and controlling it is also considered very warm and caring. This cultural phenomenon helps explain why mothers are reluctance to send children to preschool and prefer to keep them home-schooled instead. Dr. Baydar believes it is time to get creative in finding ways to get children ready to the current and future challenges of our globalized world while still accommodating different cultural contexts. Public Education tries to do exactly that.

The work suggests a distributed model of public education that would meet the children’s needs by placing
them under the command of the networked public.

A world map switching 14.5 locations per minute, each voicing its own short site-specific commands. These short commands will be contributed by visitors to the mobile app. Each would choose the location they want their command to be played in and record their short command to join a map of distributed omnipresent control.

Public Education attempts to go beyond parenting or any specific cultural phenomenon. It is an opportunity to inquire about the role and control of media in public space and to challenge the way we mindlessly rush away from old models of control and towards new ones.

Browse the commands and install the app at http://pe.mushon.com
```

Site:
http://pe.mushon.com

Images:

![screenshot-640x960-a](https://f.cloud.github.com/assets/27123/1429391/38d20ec8-40b2-11e3-8e64-9824866a65d1.png)

![screenshot-640x960-b](https://f.cloud.github.com/assets/27123/1429392/38d59b38-40b2-11e3-8bb3-aee18ba81fa1.png)

![screenshot-640x1136-a](https://f.cloud.github.com/assets/27123/1429393/38d9881a-40b2-11e3-863d-8f6b248849cf.png)

![screenshot-640x1136-b](https://f.cloud.github.com/assets/27123/1429394/38dd93d8-40b2-11e3-98b0-e6bfa2f47d3b.png)

![screenshot-1024x768-a](https://f.cloud.github.com/assets/27123/1429395/38e0bdc4-40b2-11e3-9f5a-7aebbc070468.png)

![icon-1024](https://f.cloud.github.com/assets/27123/1429396/394134b0-40b2-11e3-8305-b5ca58660512.png)
