### ISSUE TITLE
Setup pe.mushon.com as the root directory of the project

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#99]
This means sharing links should refer to that url as well.
We can either do it by installing the work on that subdomain or by [redirecting the subdomain to a gh-pages](https://help.github.com/articles/setting-up-a-custom-domain-with-pages).

**Comment by niryariv** [comment]
i pushed CNAME file per gh's protocol. @mushon please setup you DNS as explained in the page you sent. @amitaibu please merge with gh-pages when you think it's ready.

**Comment by mushon** [comment]
@niryariv the page says:

> Warning: Project pages subpaths like http://username.github.io/projectname will not be redirected to a project's custom domain.

Does this mean we will need to start a new user for this to work on the root gh-page? Or would it require us to install the app somewhere else where this DNS mapping could work?
Anyway, I have temporarily used an iFrame so http://pe.mushon.com does show the project but doesn't update the url. So for now this is only a temporary hack.

**Comment by niryariv** [comment]
i think it's irrelevant for us, it just refers to GH's auto redirection, in our case its not a subpath - ie it's pe.mushon.com rather than pe.mushon.com/somepath

**Comment by mushon** [comment]
@niryariv I would need some help on my end with that

## 

Mushon Zer-Aviv
Mushon.com (http://Mushon.com) | Shual.com (http://Shual.com) | @Mushon (http://twitter.com/mushon)

**Comment by niryariv** [comment]
no problem - ping me when you want to work on this, chat/skype/phone
